/**
 * decks.js — Perguntas do Fica pro Café
 *
 * Este arquivo contém só DADOS (perguntas e estrutura de decks). Sem lógica.
 *
 * Pra adicionar uma pergunta nova: prepende no array `questions` da categoria
 * correspondente, com um id sequencial — em PT_DECKS E EN_DECKS. Os IDs
 * precisam ser iguais nos dois (servem de referência cruzada).
 */

const PT_DECKS = [
  {
    id: 'profundas', nameKey: 'cat_profundas', questions: [
      { id: 'p1',  text: 'Qual memória da sua infância você guarda com mais carinho?' },
      { id: 'p2',  text: 'Que música ou cheiro te leva imediatamente para o passado?' },
      { id: 'p3',  text: 'Qual era a sua brincadeira favorita? Você ainda sente saudade dela?' },
      { id: 'p4',  text: 'Tem alguma tradição da sua família que você quer manter para sempre?' },
      { id: 'p5',  text: 'Qual foi o momento em que você percebeu que estava crescendo?' },
      { id: 'p6',  text: 'Tem algum lugar da sua cidade (ou do mundo) que você evita passar por causa do que ele te lembra?' },
      { id: 'p7',  text: 'Qual foi a última vez que você chorou e por quê?' },
      { id: 'p8',  text: 'Qual mentira você conta pra si mesmo e já percebeu que conta?' },
      { id: 'p9',  text: 'Tem alguma coisa que você faz só por medo de parar?' },
      { id: 'p10', text: 'O que te cansa de um jeito que você nem percebe que tá cansando?' },
      { id: 'p11', text: 'Qual versão sua dos últimos 10 anos mais se parece com a que você é hoje?' },
      { id: 'p12', text: 'Tem algo que você sabe que vai ter que encarar eventualmente mas ainda não tá pronto?' },
      { id: 'p13', text: 'Qual crítica mais dolorida você já recebeu e concordou em silêncio?' },
      { id: 'p14', text: 'O que você faz quando ninguém tá olhando e isso diz muito sobre você?' },
      { id: 'p15', text: 'Em que situação você se sente mais "você mesmo"?' },
      { id: 'p16', text: 'Tem alguma crença sua que mudou muito nos últimos anos?' },
      { id: 'p17', text: 'O que você precisa pra recarregar as energias de verdade?' },
      { id: 'p18', text: 'O que você acha difícil pedir ajuda — e por quê?' },
      { id: 'p19', text: 'O que você faria diferente se soubesse que não ia ser julgado?' },
      { id: 'p20', text: 'Qual sonho você deixou de lado que ainda pulsa de vez em quando?' },
      { id: 'p21', text: 'Se pudesse aprender qualquer coisa do zero amanhã, o que seria?' },
      { id: 'p22', text: 'Você se sente mais sozinho quando tá sozinho ou cercado de gente?' },
      { id: 'p23', text: 'Você tem medo de virar quem?' },
      { id: 'p24', text: 'Tem algo que você evita pensar a fundo porque sabe que vai mexer com você?' },
      { id: 'p25', text: 'O que você faria se descobrisse que tem 1 ano de vida? E 1 mês?' },
      { id: 'p26', text: 'O que te deixa genuinamente feliz de um jeito que é difícil explicar?' },
      { id: 'p27', text: 'Se você pudesse tirar uma coisa do mundo sem ninguém questionar, o que seria?' },
      { id: 'p28', text: 'O que faz um dia valer a pena pra você?' },
      { id: 'p29', text: 'Você acredita em destino ou em coincidências gritantes?' },
      { id: 'p30', text: 'Qual é a sua definição de sucesso hoje e era qual há 10 anos?' },
      { id: 'p31', text: 'Qual é a coisa que você faz bem e que as pessoas ao redor não percebem?' },
      { id: 'p32', text: 'Qual é o talento escondido mais inusitado que você tem?' },
      { id: 'p33', text: 'Qual foi a última vez que você se sentiu genuinamente orgulhoso de si mesmo?' },
      { id: 'p34', text: 'Tem alguma coisa que você acha que só você enxerga sobre você mesmo?' },
      { id: 'p35', text: 'Qual hábito seu você gostaria de passar adiante, tipo herança?' },
      { id: 'p36', text: 'Qual é a escolha que você fez que parecia pequena na hora, mas mudou tudo?' },
      { id: 'p37', text: 'Você se perdoaria hoje por algo que ainda se cobra?' },
      { id: 'p38', text: 'Qual é o elogio que você tem mais dificuldade de aceitar?' },
      { id: 'p39', text: 'O que você costumava achar importante e hoje acha bobagem?' },
      { id: 'p40', text: 'Qual fase da sua vida você menos gostaria de reviver e qual você viveria de novo agora?' },
      { id: 'p41', text: 'O que você mais admira em quem está aqui com você agora?' },
      { id: 'p42', text: 'Qual foi a conversa que mais te transformou na vida?' },
      { id: 'p43', text: 'Como você percebe que realmente confia em alguém?' },
      { id: 'p44', text: 'Tem uma pessoa que mudou o seu jeito de ver o mundo? Como?' },
      { id: 'p45', text: 'Qual é o seu jeito favorito de demonstrar carinho?' },
      { id: 'p46', text: 'Como você quer ser lembrado pelas pessoas que te amam?' },
      { id: 'p47', text: 'Tem alguém que você deve um pedido de desculpas que nunca fez?' },
      { id: 'p48', text: 'Qual é a diferença, pra você, entre gostar de alguém e amar?' },
      { id: 'p49', text: 'O que faz uma amizade ficar, mesmo depois de anos sem se falar?' },
      { id: 'p50', text: 'Como você sabe que é hora de se afastar de alguém?' },
      { id: 'p51', text: 'Tem alguém que você admira mas nunca disse isso diretamente pra pessoa?' },
      { id: 'p52', text: 'O que uma pessoa precisa fazer pra perder a sua confiança de vez?' },
      { id: 'p53', text: 'Qual relação da sua vida te ensinou mais sobre você mesmo?' },
      { id: 'p54', text: 'O que faz você se sentir visto de verdade por alguém?' },
      { id: 'p55', text: 'Tem alguém que você perdeu contato e pensa de vez em quando como será que tá?' },
      { id: 'p56', text: 'Qual é o tipo de presença que te faz bem, mesmo em silêncio?' },
      { id: 'p57', text: 'Você consegue perceber quando uma pessoa tá fingindo estar bem? Como?' },
      { id: 'p58', text: 'O que você faz quando percebe que magoou alguém sem querer?' },
      { id: 'p59', text: 'Tem algum relacionamento (de qualquer tipo) que você deveria ter terminado antes e não teve coragem?' },
      { id: 'p60', text: 'O que é deal breaker pra você numa amizade? E num relacionamento?' },
      { id: 'p61', text: 'Você se reconcilia fácil ou carrega ressentimento?' },
      { id: 'p62', text: 'Quando foi a última vez que você se sentiu realmente cuidado por alguém?' },
      { id: 'p63', text: 'Tem alguma pessoa na sua vida que você ama mas teria dificuldade de conviver?' },
      { id: 'p64', text: 'Qual versão de você foi mais difícil de deixar pra trás?' },
      { id: 'p65', text: 'Tem algum sentimento que você sente vergonha de sentir?' },
      { id: 'p66', text: 'Qual é o "mantra" silencioso que você repete pra se convencer de algo?' },
      { id: 'p67', text: 'Qual dor antiga você ainda carrega que ninguém à sua volta sabe?' },
      { id: 'p68', text: 'Qual é a coisa mais bonita que alguém já te disse?' },
      { id: 'p69', text: 'Você tem mais medo de estagnar ou de mudar? Por quê?' },
      { id: 'p70', text: 'Tem algum elogio que você morre de vontade de receber e nunca recebe?' },
      { id: 'p71', text: 'Qual é a frase que você mais escutou na infância e ainda ecoa em você?' },
      { id: 'p72', text: 'Tem alguma coisa boa na sua vida que você ainda acha que não merece?' },
      { id: 'p73', text: 'Qual foi a última coisa que te fez parar tudo e respirar fundo?' },
      { id: 'p74', text: 'Tem algum filme/livro que você assistiu/leu na hora errada e quer revisitar?' },
      { id: 'p75', text: 'Qual é o tipo de pessoa que te intimida e por quê?' },
      { id: 'p76', text: 'Em que área da sua vida você se sabota com mais frequência?' },
      { id: 'p77', text: 'Qual emoção você tem mais dificuldade de expressar?' },
      { id: 'p78', text: 'Tem alguma coisa que você acha que vai te perseguir até o fim?' },
      { id: 'p79', text: 'O que você descobriu sobre si mesmo que ninguém te avisou?' },
      { id: 'p80', text: 'Qual é o seu jeito de se autopunir que ninguém percebe?' },
      { id: 'p81', text: 'Qual é o medo de criança que ainda mora em você?' },
      { id: 'p82', text: 'Qual é o tipo de fracasso que mais te assombra?' },
      { id: 'p83', text: 'Qual gesto pequeno alguém faz por você que você nunca disse que percebe?' },
      { id: 'p84', text: 'O que você só consegue ser/fazer perto de uma pessoa específica?' },
      { id: 'p85', text: 'Como você reconhece quando uma pessoa entrou na sua vida pra ficar?' },
      { id: 'p86', text: 'Tem alguém na sua vida que você considera família mesmo sem ser de sangue?' },
      { id: 'p87', text: 'Você prefere ser entendido ou ser ouvido?' },
      { id: 'p88', text: 'Tem alguém de quem você tem ciúmes de um jeito que não saberia explicar?' },
      { id: 'p89', text: 'Qual amizade da sua vida você acha que é mais profunda do que a outra pessoa imagina?' },
      { id: 'p90', text: 'Tem alguém com quem você consegue ficar em silêncio sem desconforto?' },
      { id: 'p91', text: 'O que você acha mais difícil: pedir desculpa ou aceitar uma?' },
      { id: 'p92', text: 'Qual é o tipo de afeto que te emociona mais: gesto, palavra, presença ou tempo?' },
      { id: 'p93', text: 'Tem alguém que te ama de um jeito que você não sabe receber?' },
      { id: 'p94', text: 'Você é melhor amigo, melhor parceiro, melhor filho, ou melhor pai/mãe?' },
      { id: 'p95', text: 'Você consegue admirar alguém sem se comparar?' },
      { id: 'p96', text: 'O que você não conta nem pra quem você confia mais?' },
      { id: 'p97', text: 'Qual foi o último gesto de afeto que te pegou desprevenido?' }
    ]
  },
  {
    id: 'divertidas', nameKey: 'cat_divertidas', questions: [
      { id: 'd1',  text: 'Se você fosse um prato de comida, qual seria?' },
      { id: 'd2',  text: 'Qual foi a gargalhada mais incontrolável que você já deu?' },
      { id: 'd3',  text: 'Se você pudesse trocar de vida por um dia com alguém, quem seria?' },
      { id: 'd4',  text: 'Qual série, livro ou filme você indicaria pra todo mundo sem hesitar?' },
      { id: 'd5',  text: 'Se pudesse viver dentro de um livro, filme ou série por um ano, qual seria?' },
      { id: 'd6',  text: 'Se você pudesse mandar uma única mensagem pra humanidade inteira ao mesmo tempo, qual seria?' },
      { id: 'd7',  text: 'Se você pudesse adicionar um feriado ao calendário, seria qual?' },
      { id: 'd8',  text: 'Se você fosse eleito presidente de um país minúsculo, qual seria sua primeira lei?' },
      { id: 'd9',  text: 'Se você abrisse uma loja de um produto só, que produto seria?' },
      { id: 'd10', text: 'Se você pudesse apagar uma música do mundo pra sempre, qual seria?' },
      { id: 'd11', text: 'Qual alimento você defenderia num tribunal?' },
      { id: 'd12', text: 'Qual superpoder inútil você adoraria ter?' },
      { id: 'd13', text: 'Qual teoria da conspiração maluca você secretamente acha que pode ser verdade?' },
      { id: 'd14', text: 'Se você tivesse que substituir todas as suas roupas por uma única peça pra sempre, qual seria?' },
      { id: 'd15', text: 'Qual é a coisa mais idiota que já te fez chorar?' },
      { id: 'd16', text: 'Se você tivesse que ganhar a vida fazendo um podcast sobre um assunto muito específico, seria sobre o quê?' },
      { id: 'd17', text: 'Qual é o pior nome que você já ouviu alguém dar pra um filho ou pet?' },
      { id: 'd18', text: 'Qual tarefa doméstica você faria com gosto se te pagassem bem, e qual você não faria nem por milhão?' },
      { id: 'd19', text: 'Qual som do dia a dia te irrita de um jeito desproporcional?' },
      { id: 'd20', text: 'Qual é o maior feito inútil de que você tem orgulho?' },
      { id: 'd21', text: 'Se você pudesse proibir uma gíria ou jargão pra sempre, qual seria?' },
      { id: 'd22', text: 'Qual é a sua obsessão mais idiota dos últimos tempos?' },
      { id: 'd23', text: 'Se seu cérebro fosse um navegador, quantas abas estariam abertas agora?' },
      { id: 'd24', text: 'Qual desenho animado você assistiria hoje sem nenhuma vergonha?' },
      { id: 'd25', text: 'Se você pudesse possuir um único objeto inútil caríssimo, qual seria?' },
      { id: 'd26', text: 'Qual é a coisa mais vergonha alheia que você já fez por amor?' },
      { id: 'd27', text: 'Se você fosse obrigado a tatuar a primeira coisa que te vier na cabeça agora, qual seria?' },
      { id: 'd28', text: 'Qual é a sua história mais absurda envolvendo álcool, sem nomes pra proteger os culpados?' },
      { id: 'd29', text: 'Se você pudesse falar com animais mas só com uma espécie, qual escolheria?' },
      { id: 'd30', text: 'Qual é o seu guilty pleasure mais indefensável?' },
      { id: 'd31', text: 'Qual é a briga mais idiota que você já comprou com alguém?' },
      { id: 'd32', text: 'Se o inferno existisse e fosse personalizado pra você, como seria o seu?' },
      { id: 'd33', text: 'Qual é o conhecimento mais inútil que você tem armazenado e nunca esquece?' },
      { id: 'd34', text: 'Qual personagem fictício seria insuportável de conviver na vida real?' },
      { id: 'd35', text: 'Qual é a sua opinião impopular sobre algo banal que você defende com unhas e dentes?' },
      { id: 'd36', text: 'Qual filme você se recusa a assistir e nem sabe direito por quê?' },
      { id: 'd37', text: 'Qual é a sua descoberta culinária mais inusitada dos últimos tempos?' },
      { id: 'd38', text: 'Se você pudesse resolver UM mistério do mundo, qual escolheria?' },
      { id: 'd39', text: 'Se você fosse obrigado a ter uma frase tatuada na anca direita da bunda, qual seria? E na esquerda? E por que tem diferença?' },
      { id: 'd40', text: 'Qual é o pior conselho que você já seguiu?' },
      { id: 'd41', text: 'Se você pudesse roubar a habilidade de uma pessoa, de quem e qual?' },
      { id: 'd42', text: 'Se animais pudessem twittar, quem seria o mais polêmico?' },
      { id: 'd43', text: 'Se você pudesse extinguir uma palavra do português, qual seria?' },
      { id: 'd44', text: 'Que tipo de loucura você faria de propósito se ninguém soubesse?' },
      { id: 'd45', text: 'Qual é a textura de comida que você não tolera?' },
      { id: 'd46', text: 'Se você fosse fantasma, quem você assombraria primeiro?' },
      { id: 'd47', text: 'Qual é o item mais inútil que você tem na sua casa há mais de 1 ano?' },
      { id: 'd48', text: 'Se você pudesse ser fluente em 3 idiomas amanhã, quais escolheria e por quê?' },
      { id: 'd49', text: 'Qual é a sua palavra favorita só pelo som?' },
      { id: 'd50', text: 'Se você morresse e voltasse como animal, mas decidisse a espécie, qual seria?' },
      { id: 'd51', text: 'Que objeto seu te trairia se falasse?' },
      { id: 'd52', text: 'Qual hobby você só não tem porque dá trabalho começar?' },
      { id: 'd53', text: 'Qual é a sua "mentira branca" preferida em situação social?' },
      { id: 'd54', text: 'Se você fosse fundador de uma seita, qual seria o ritual obrigatório?' },
      { id: 'd55', text: 'Se você pudesse esquecer um livro/filme/série pra vivenciar de novo pela primeira vez, qual?' },
      { id: 'd56', text: 'Qual é o seu maior preconceito contra um nome de pessoa?' },
      { id: 'd57', text: 'Qual rotina de outras pessoas você acha completamente alienígena?' },
      { id: 'd58', text: 'Qual lugar do mundo você não tem nenhum interesse em visitar e por quê?' },
      { id: 'd59', text: 'Que erro de português alheio te dá uma raiva visceral injustificada?' },
      { id: 'd60', text: 'Qual é a obsessão visual mais boba que você tem (ex: pastas organizadas, ladrilhos, etc)?' },
      { id: 'd61', text: 'Se fosse jurado de reality show, que estereótipo você seria?' },
      { id: 'd62', text: 'Qual é o pior conselho que você daria de boa fé?' },
      { id: 'd63', text: 'Se você fundasse uma cidade, qual seria a primeira lei "estranha" mas inegociável?' },
      { id: 'd64', text: 'Qual é o pior e o melhor nome de loja/restaurante que você já viu?' },
      { id: 'd65', text: 'Qual seu pior vício de linguagem?' },
      { id: 'd66', text: 'Se você fosse forçado a fazer cosplay agora com o que tem em casa, de quem seria?' },
      { id: 'd67', text: 'Qual é o seu maior desencontro com seu signo? (mesmo que não acredite)' },
      { id: 'd68', text: 'Se você fosse contratado pra escrever a placa de um banheiro público, o que ela diria?' },
      { id: 'd69', text: 'Qual é o seu critério não-negociável pra um lanche bom?' },
      { id: 'd70', text: 'Se você pudesse desinventar uma rede social, qual seria?' },
      { id: 'd71', text: 'Qual a sua opinião sobre queijos no geral?' },
      { id: 'd72', text: 'Que pequeno luxo você só percebe que ama quando não tem?' },
      { id: 'd73', text: 'Se você herdasse uma loja por engano, qual seria o setor mais decepcionante de herdar?' },
      { id: 'd74', text: 'Em qual setor do mercado seria mais provável te encontrar?' },
      { id: 'd75', text: 'Qual é o pior elogio disfarçado que você já recebeu?' },
      { id: 'd76', text: 'Qual sabor de bolo de aniversário você repudia?' },
      { id: 'd77', text: 'Se eu falo pra você: "pensa numa maçã", como você imagina? (imagem como uma foto, sabor, som...)' },
      { id: 'd78', text: 'Se você fosse um sabor de sorvete que ninguém pede, qual seria?' },
      { id: 'd79', text: 'Qual é a pior combinação de cores (paleta) que você já viu?' },
      { id: 'd80', text: 'Que tipo de roupa te dá uma sensação de "personagem"?' },
      { id: 'd81', text: 'Qual é o pior tipo de espera (fila de banco, médico, transporte público)?' },
      { id: 'd82', text: 'Qual é a coisa mais "vovó" que você faz sem perceber?' },
      { id: 'd83', text: 'Se você tivesse que viver dentro de um quadro famoso por 1 dia, qual seria?' },
      { id: 'd84', text: 'Se você abrisse um café cuja regra fosse "só pode entrar com X", qual seria o X?' },
      { id: 'd85', text: 'Qual livro/filme/série todo mundo ama e você acha bem mediano?' }
    ]
  },
  {
    id: 'grupo', nameKey: 'cat_grupo', questions: [
      { id: 'g1',  text: 'Se todos daqui adquirissem super poderes, quem seria mais provável virar vilão?' },
      { id: 'g2',  text: 'Quem daqui você acha que tá vivendo a melhor fase da vida agora?' },
      { id: 'g3',  text: 'Se esse grupo abrisse um negócio juntos, seria qual e quem faria o quê?' },
      { id: 'g4',  text: 'Qual de nós você acha que mais mudou nos últimos 5 anos?' },
      { id: 'g5',  text: 'Se fôssemos uma série, quem seria o personagem principal? E quem seria o alívio cômico?' },
      { id: 'g6',  text: 'Quem daqui você chamaria pra resolver qual tipo de problema?' },
      { id: 'g7',  text: 'Qual é a sua memória favorita com alguém desse grupo?' },
      { id: 'g8',  text: 'Se tivéssemos que sobreviver numa ilha deserta, qual seria a função de cada um?' },
      { id: 'g9',  text: 'Qual de nós daria o pior conselho amoroso com a maior confiança?' },
      { id: 'g10', text: 'Quem aqui você confiaria pra te ligar às 4 da manhã, e quem você nunca atenderia nesse horário?' },
      { id: 'g11', text: 'Se tivéssemos que viver juntos por 1 mês numa casa só, quem seria o primeiro a surtar?' },
      { id: 'g12', text: 'Qual história desse grupo a gente vai continuar contando daqui a 20 anos?' },
      { id: 'g13', text: 'Quem aqui mais mudou sem perceber que mudou?' },
      { id: 'g14', text: 'Quem daqui você acha que tem a pior música preferida em segredo?' },
      { id: 'g15', text: 'Se alguém daqui virasse rico da noite pro dia, quem a gente teria mais medo do que ia fazer?' },
      { id: 'g16', text: 'Qual é a primeira impressão que você teve de cada pessoa aqui (podem ir um por um)?' },
      { id: 'g17', text: 'Qual de nós tem mais chance de envelhecer e virar aquele tio/tia excêntrico que todo mundo adora?' },
      { id: 'g18', text: 'Quem aqui você pegaria emprestado pra apresentar pros seus pais numa emergência?' },
      { id: 'g19', text: 'Qual de nós você escolheria pra fazer dupla em escape room, e qual você recusaria educadamente?' },
      { id: 'g20', text: 'Quem aqui você acha que mais te conhece de verdade?' },
      { id: 'g21', text: 'Se fôssemos personagens de uma mesa de RPG, qual classe cada um seria?' },
      { id: 'g22', text: 'Qual foi a vez que alguém do grupo te surpreendeu de um jeito que você ainda lembra, pra melhor ou pra pior?' },
      { id: 'g23', text: 'Se um de nós sumisse sem avisar, quem seria o primeiro a notar?' },
      { id: 'g24', text: 'Qual de nós você acha que tá escondendo o maior segredo agora, mesmo sem prova nenhuma?' },
      { id: 'g25', text: 'Quem daqui você chamaria pra um road trip sem destino definido?' },
      { id: 'g26', text: 'Se fôssemos um grupo de super-heróis, qual seria a fraqueza coletiva de todo mundo?' },
      { id: 'g27', text: 'Quem daqui mais mudou a sua vida de algum jeito, grande ou pequeno?' },
      { id: 'g28', text: 'Qual versão de cada um de nós (há 5, 10 anos atrás) você mais gostaria de reencontrar por uma noite?' },
      { id: 'g29', text: 'Se a gente tivesse que fazer um brinde agora pra alguém do grupo, pra quem seria e por quê?' },
      { id: 'g30', text: 'Qual de nós sairia de um apocalipse com a história mais absurda pra contar?' },
      { id: 'g31', text: 'Qual de nós fala com IA como se fosse gente?' },
      { id: 'g32', text: 'Qual de nós você chamaria pra A) emergência médica; B) emergência emocional e C) emergência do trânsito?' },
      { id: 'g33', text: 'Quem aqui você acha que tá guardando uma opinião sobre alguém do grupo que nunca falou em voz alta?' },
      { id: 'g34', text: 'Qual seria a frase tatuada na testa de cada um se a gente fosse honesto?' },
      { id: 'g35', text: 'Quem aqui o grupo defenderia mesmo sabendo que ele/ela tá errado?' },
      { id: 'g36', text: 'Qual de nós é o "termômetro emocional" do grupo?' },
      { id: 'g37', text: 'Qual de nós tem o melhor senso de direção e qual se perde no shopping?' },
      { id: 'g38', text: 'Qual de nós tem mais "papel" pra cargos de chefia no futuro?' },
      { id: 'g39', text: 'Quem você ouviria sem questionar mesmo se discordasse profundamente?' },
      { id: 'g40', text: 'Qual de nós tem a maior chance de ficar famoso por algo polêmico?' },
      { id: 'g41', text: 'Quem aqui já te salvou sem saber que salvou?' },
      { id: 'g42', text: 'Qual é o "talento secreto" que você acha que cada um tem?' },
      { id: 'g43', text: 'Quem aqui tem o gosto musical mais difícil de explicar?' },
      { id: 'g44', text: 'Qual de nós seria o pior inimigo se virasse vilão?' },
      { id: 'g45', text: 'Quem aqui tá lidando com mais coisa em silêncio do que demonstra?' },
      { id: 'g46', text: 'Quem aqui mais te inspira em algo específico que nunca falou em voz alta?' },
      { id: 'g47', text: 'Qual de nós tem a história mais subestimada?' },
      { id: 'g48', text: 'Quem você chamaria pra um conselho de carreira? E pra um conselho de amor?' },
      { id: 'g49', text: 'Qual de nós é mais provável de aparecer num documentário sobre algum assunto bizarro?' },
      { id: 'g50', text: 'Quem aqui você acha que tem o pior gosto pra parceiros românticos?' },
      { id: 'g51', text: 'Qual de nós seria o pior testemunho num tribunal?' },
      { id: 'g52', text: 'Quem aqui você confiaria pra cuidar das suas plantas por 1 mês?' },
      { id: 'g53', text: 'Quem aqui mais te tira do sério mas você continua amando?' },
      { id: 'g54', text: 'Qual de nós é o mais rancoroso disfarçado?' },
      { id: 'g55', text: 'Se a gente pudesse trocar uma característica de cada um, qual seria a mais óbvia?' },
      { id: 'g56', text: 'Quem aqui mais sabe o que quer da vida?' },
      { id: 'g57', text: 'Qual de nós tem mais cara de quem está vivendo uma vida secreta?' },
      { id: 'g58', text: 'Quem aqui você quer ainda na sua vida quando tiver 70 anos?' },
      { id: 'g59', text: 'Se a gente tivesse que indicar UMA pessoa do grupo pra escrever um livro, quem seria e qual seria o título provável?' },
      { id: 'g60', text: 'Qual é a história desse grupo que ainda dá vergonha alheia de contar pra terceiros?' },
      { id: 'g61', text: 'Qual é o lugar que carrega mais memória desse grupo?' },
      { id: 'g62', text: 'O que esse grupo tem que outros grupos da sua vida não têm?' },
      { id: 'g63', text: 'Como vocês acham que esse grupo seria visto de fora por um observador?' },
      { id: 'g64', text: 'Qual é a coisa mais bonita que aconteceu nesse grupo nos últimos 12 meses?' },
      { id: 'g65', text: 'Se esse grupo fosse um organismo vivo, qual órgão cada um seria?' },
      { id: 'g66', text: 'Que tipo de pessoa nova encaixaria nesse grupo, e que tipo nunca daria certo?' },
      { id: 'g67', text: 'Se esse grupo ganhasse um prêmio coletivo, qual seria a categoria?' },
      { id: 'g68', text: 'Quais são as 3 regras não-ditas desse grupo?' },
      { id: 'g69', text: 'Em qual assunto a gente diverge mais quando vem à tona?' },
      { id: 'g70', text: 'Qual decisão coletiva esse grupo tomaria com facilidade e qual seria caos?' },
      { id: 'g71', text: 'Qual é a opinião mais polêmica que circula nesse grupo?' },
      { id: 'g72', text: 'Se a gente fosse passar 1 mês juntos numa casa de praia, qual a maior briga inevitável?' },
      { id: 'g73', text: 'Se a gente abrisse um podcast agora, qual seria o tema?' },
      { id: 'g74', text: 'Se esse grupo participasse de um reality coletivo, ganharíamos ou seríamos expulsos primeiro?' },
      { id: 'g75', text: 'Se a gente pudesse vetar um traço de personalidade coletivo do grupo, qual seria?' },
      { id: 'g76', text: 'Tem algum elogio que você queria fazer pra alguém aqui agora e nunca fez?' },
      { id: 'g77', text: 'Tem algo que aconteceu nesse grupo que mudou seu jeito de ver as pessoas?' },
      { id: 'g78', text: 'Quando esse grupo te frustra, o que normalmente é a causa?' },
      { id: 'g79', text: 'Qual é a sua memória favorita envolvendo apenas você e UMA outra pessoa daqui?' },
      { id: 'g80', text: 'Você se sente mais você ou menos você nesse grupo?' },
      { id: 'g81', text: 'Se a gente tivesse que adotar um "bicho de estimação coletivo", qual e quem cuidaria de quê?' },
      { id: 'g82', text: 'Qual é o primeiro adjetivo que vem na sua cabeça quando pensa nesse grupo coletivamente?' },
      { id: 'g83', text: 'Qual é a comida que combina mais com a vibe desse grupo?' },
      { id: 'g84', text: 'Qual é a memória mais antiga que você tem envolvendo todo mundo daqui?' },
      { id: 'g85', text: 'Tem alguém daqui que você gostaria de conhecer melhor?' },
      { id: 'g86', text: 'O que mudou em você desde que esse grupo entrou na sua vida?' },
      { id: 'g87', text: 'Qual é o assunto que esse grupo abre que outros grupos seus nunca tocariam?' },
      { id: 'g88', text: 'O que esse grupo precisa fazer mais e o que precisa fazer menos?' },
      { id: 'g89', text: 'Se a gente tivesse que escrever um manual pra um membro novo entrar, qual seria a primeira regra?' },
      { id: 'g90', text: 'Qual é a sua maior gratidão em relação a esse grupo?' },
      { id: 'g91', text: 'Tem alguém aqui com quem você tem um afeto específico que não tem com mais ninguém?' }
    ]
  }
];

const EN_DECKS = [
  {
    id: 'profundas', nameKey: 'cat_profundas', questions: [
      { id: 'p1',  text: 'Which childhood memory do you hold closest to your heart?' },
      { id: 'p2',  text: 'What song or smell takes you straight back to the past?' },
      { id: 'p3',  text: 'What was your favorite childhood game? Do you still miss it?' },
      { id: 'p4',  text: 'Is there a family tradition you want to keep alive forever?' },
      { id: 'p5',  text: 'When did you realize you were growing up?' },
      { id: 'p6',  text: 'Is there a place in your city (or in the world) you avoid because of what it reminds you of?' },
      { id: 'p7',  text: 'When was the last time you cried, and why?' },
      { id: 'p8',  text: 'What lie do you tell yourself that you\'ve already noticed you tell?' },
      { id: 'p9',  text: 'Is there something you only do out of fear of stopping?' },
      { id: 'p10', text: 'What drains you in a way you don\'t even notice it\'s draining you?' },
      { id: 'p11', text: 'Which version of you from the last 10 years feels most like the person you are today?' },
      { id: 'p12', text: 'Is there something you know you\'ll have to face eventually but you\'re not ready yet?' },
      { id: 'p13', text: 'What was the most painful criticism you\'ve received that you silently agreed with?' },
      { id: 'p14', text: 'What do you do when no one is watching that says a lot about you?' },
      { id: 'p15', text: 'In what kind of situation do you feel most like "yourself"?' },
      { id: 'p16', text: 'Is there a belief of yours that has changed a lot in recent years?' },
      { id: 'p17', text: 'What do you actually need to truly recharge?' },
      { id: 'p18', text: 'What do you find hardest about asking for help — and why?' },
      { id: 'p19', text: 'What would you do differently if you knew you wouldn\'t be judged?' },
      { id: 'p20', text: 'Which dream did you set aside that still flickers every now and then?' },
      { id: 'p21', text: 'If you could learn anything from scratch tomorrow, what would it be?' },
      { id: 'p22', text: 'Do you feel lonelier when you\'re alone or when you\'re surrounded by people?' },
      { id: 'p23', text: 'Who are you afraid of becoming?' },
      { id: 'p24', text: 'Is there something you avoid thinking about deeply because you know it would shake you?' },
      { id: 'p25', text: 'What would you do if you found out you had 1 year to live? And 1 month?' },
      { id: 'p26', text: 'What makes you genuinely happy in a way that\'s hard to put into words?' },
      { id: 'p27', text: 'If you could remove one thing from the world without anyone questioning it, what would it be?' },
      { id: 'p28', text: 'What makes a day worth it for you?' },
      { id: 'p29', text: 'Do you believe in fate or in striking coincidences?' },
      { id: 'p30', text: 'What\'s your definition of success today, and what was it 10 years ago?' },
      { id: 'p31', text: 'What\'s something you do well that the people around you don\'t notice?' },
      { id: 'p32', text: 'What\'s the most unusual hidden talent you have?' },
      { id: 'p33', text: 'When was the last time you felt genuinely proud of yourself?' },
      { id: 'p34', text: 'Is there something about yourself that you think only you can see?' },
      { id: 'p35', text: 'Which habit of yours would you want to pass on, like an inheritance?' },
      { id: 'p36', text: 'What\'s a choice you made that seemed small at the time but changed everything?' },
      { id: 'p37', text: 'Could you forgive yourself today for something you still hold against yourself?' },
      { id: 'p38', text: 'Which compliment do you have the hardest time accepting?' },
      { id: 'p39', text: 'What did you used to think was important that now feels silly?' },
      { id: 'p40', text: 'Which phase of your life would you least want to relive, and which would you live again right now?' },
      { id: 'p41', text: 'What do you most admire about whoever is here with you right now?' },
      { id: 'p42', text: 'What conversation transformed you the most in your life?' },
      { id: 'p43', text: 'How do you know when you really trust someone?' },
      { id: 'p44', text: 'Is there a person who changed the way you see the world? How?' },
      { id: 'p45', text: 'What\'s your favorite way to show affection?' },
      { id: 'p46', text: 'How do you want to be remembered by the people who love you?' },
      { id: 'p47', text: 'Is there someone you owe an apology to that you never made?' },
      { id: 'p48', text: 'For you, what\'s the difference between liking someone and loving them?' },
      { id: 'p49', text: 'What makes a friendship last, even after years without talking?' },
      { id: 'p50', text: 'How do you know when it\'s time to walk away from someone?' },
      { id: 'p51', text: 'Is there someone you admire but have never told them directly?' },
      { id: 'p52', text: 'What does someone have to do to lose your trust for good?' },
      { id: 'p53', text: 'Which relationship in your life has taught you the most about yourself?' },
      { id: 'p54', text: 'What makes you feel truly seen by someone?' },
      { id: 'p55', text: 'Is there someone you\'ve lost touch with and wonder about every now and then?' },
      { id: 'p56', text: 'What kind of presence makes you feel good, even in silence?' },
      { id: 'p57', text: 'Can you tell when someone is pretending to be okay? How?' },
      { id: 'p58', text: 'What do you do when you realize you\'ve hurt someone unintentionally?' },
      { id: 'p59', text: 'Is there a relationship (of any kind) you should have ended sooner but didn\'t have the courage to?' },
      { id: 'p60', text: 'What\'s a deal breaker for you in a friendship? And in a relationship?' },
      { id: 'p61', text: 'Do you reconcile easily or do you carry resentment?' },
      { id: 'p62', text: 'When was the last time you felt truly cared for by someone?' },
      { id: 'p63', text: 'Is there someone in your life you love but would have a hard time living with?' },
      { id: 'p64', text: 'Which version of yourself was hardest to leave behind?' },
      { id: 'p65', text: 'Is there a feeling you\'re ashamed of feeling?' },
      { id: 'p66', text: 'What\'s the silent "mantra" you repeat to convince yourself of something?' },
      { id: 'p67', text: 'What old pain do you still carry that no one around you knows about?' },
      { id: 'p68', text: 'What\'s the most beautiful thing someone has ever said to you?' },
      { id: 'p69', text: 'Are you more afraid of stagnating or of changing? Why?' },
      { id: 'p70', text: 'Is there a compliment you\'re dying to receive that you never get?' },
      { id: 'p71', text: 'What\'s a phrase you heard most in childhood that still echoes in you?' },
      { id: 'p72', text: 'Is there something good in your life that you still feel you don\'t deserve?' },
      { id: 'p73', text: 'What was the last thing that made you stop everything and take a deep breath?' },
      { id: 'p74', text: 'Is there a movie/book you watched/read at the wrong time and want to revisit?' },
      { id: 'p75', text: 'What kind of person intimidates you and why?' },
      { id: 'p76', text: 'In what area of your life do you self-sabotage most often?' },
      { id: 'p77', text: 'Which emotion do you have the hardest time expressing?' },
      { id: 'p78', text: 'Is there something you think will haunt you to the end?' },
      { id: 'p79', text: 'What did you discover about yourself that no one warned you about?' },
      { id: 'p80', text: 'What\'s your way of punishing yourself that no one notices?' },
      { id: 'p81', text: 'What\'s the childhood fear that still lives in you?' },
      { id: 'p82', text: 'What kind of failure haunts you the most?' },
      { id: 'p83', text: 'What small gesture does someone do for you that you\'ve never told them you noticed?' },
      { id: 'p84', text: 'What can you only be/do around one specific person?' },
      { id: 'p85', text: 'How do you recognize when a person has come into your life to stay?' },
      { id: 'p86', text: 'Is there someone in your life you consider family even without the blood?' },
      { id: 'p87', text: 'Do you prefer to be understood or to be heard?' },
      { id: 'p88', text: 'Is there someone you feel jealous of in a way you couldn\'t quite explain?' },
      { id: 'p89', text: 'Which friendship in your life do you think runs deeper than the other person realizes?' },
      { id: 'p90', text: 'Is there someone you can sit in silence with, no discomfort?' },
      { id: 'p91', text: 'Which is harder for you: apologizing or accepting an apology?' },
      { id: 'p92', text: 'Which kind of affection moves you most: gesture, words, presence, or time?' },
      { id: 'p93', text: 'Is there someone who loves you in a way you don\'t know how to receive?' },
      { id: 'p94', text: 'Are you a better friend, partner, child, or parent?' },
      { id: 'p95', text: 'Can you admire someone without comparing yourself to them?' },
      { id: 'p96', text: 'What do you not even tell the person you trust most?' },
      { id: 'p97', text: 'What was the last gesture of affection that caught you off guard?' }
    ]
  },
  {
    id: 'divertidas', nameKey: 'cat_divertidas', questions: [
      { id: 'd1',  text: 'If you were a dish, what would you be?' },
      { id: 'd2',  text: 'What was the most uncontrollable burst of laughter you\'ve ever had?' },
      { id: 'd3',  text: 'If you could swap lives with someone for a day, who would it be?' },
      { id: 'd4',  text: 'What show, book, or movie would you recommend to anyone, no hesitation?' },
      { id: 'd5',  text: 'If you could live inside a book, movie, or show for a year, which one would it be?' },
      { id: 'd6',  text: 'If you could send a single message to all of humanity at once, what would it be?' },
      { id: 'd7',  text: 'If you could add one holiday to the calendar, what would it be?' },
      { id: 'd8',  text: 'If you were elected president of a tiny country, what would your first law be?' },
      { id: 'd9',  text: 'If you opened a single-product store, what would you sell?' },
      { id: 'd10', text: 'If you could erase one song from the world forever, which one?' },
      { id: 'd11', text: 'Which food would you defend in court?' },
      { id: 'd12', text: 'What useless superpower would you love to have?' },
      { id: 'd13', text: 'What wild conspiracy theory do you secretly think might be true?' },
      { id: 'd14', text: 'If you had to replace your entire wardrobe with one piece of clothing forever, what would it be?' },
      { id: 'd15', text: 'What\'s the dumbest thing that ever made you cry?' },
      { id: 'd16', text: 'If you had to make a living running a podcast on a very specific topic, what would it be about?' },
      { id: 'd17', text: 'What\'s the worst name you\'ve ever heard someone give a kid or a pet?' },
      { id: 'd18', text: 'Which household chore would you happily do if paid well, and which wouldn\'t you do for a million bucks?' },
      { id: 'd19', text: 'What everyday sound annoys you in a way that feels disproportionate?' },
      { id: 'd20', text: 'What\'s the most pointless achievement you\'re proud of?' },
      { id: 'd21', text: 'If you could ban one slang word or jargon term forever, what would it be?' },
      { id: 'd22', text: 'What\'s your dumbest obsession lately?' },
      { id: 'd23', text: 'If your brain were a browser, how many tabs would be open right now?' },
      { id: 'd24', text: 'What cartoon would you watch today without any embarrassment?' },
      { id: 'd25', text: 'If you could own one ridiculously expensive useless object, what would it be?' },
      { id: 'd26', text: 'What\'s the most secondhand-embarrassment-worthy thing you\'ve ever done for love?' },
      { id: 'd27', text: 'If you were forced to tattoo the first thing that pops into your head right now, what would it be?' },
      { id: 'd28', text: 'What\'s your most absurd story involving alcohol, no names to protect the guilty?' },
      { id: 'd29', text: 'If you could talk to animals but only to one species, which would you pick?' },
      { id: 'd30', text: 'What\'s your most indefensible guilty pleasure?' },
      { id: 'd31', text: 'What\'s the dumbest fight you\'ve ever picked with someone?' },
      { id: 'd32', text: 'If hell existed and was personalized just for you, what would yours look like?' },
      { id: 'd33', text: 'What\'s the most useless piece of knowledge you have stored and never forget?' },
      { id: 'd34', text: 'Which fictional character would be unbearable to live with in real life?' },
      { id: 'd35', text: 'What\'s your unpopular opinion about something trivial that you defend tooth and nail?' },
      { id: 'd36', text: 'What movie do you refuse to watch and don\'t even quite know why?' },
      { id: 'd37', text: 'What\'s the most unusual culinary discovery you\'ve made recently?' },
      { id: 'd38', text: 'If you could solve ONE mystery in the world, which would you pick?' },
      { id: 'd39', text: 'If you were forced to tattoo a phrase on your right butt cheek, what would it be? And on the left? And why are they different?' },
      { id: 'd40', text: 'What\'s the worst advice you\'ve ever followed?' },
      { id: 'd41', text: 'If you could steal one person\'s skill, whose and which?' },
      { id: 'd42', text: 'If animals could tweet, who\'d be the most controversial?' },
      { id: 'd43', text: 'If you could remove one word from your language forever, which would it be?' },
      { id: 'd44', text: 'What kind of madness would you do on purpose if no one would know?' },
      { id: 'd45', text: 'What food texture can\'t you stand?' },
      { id: 'd46', text: 'If you were a ghost, who would you haunt first?' },
      { id: 'd47', text: 'What\'s the most useless item you\'ve had in your house for over a year?' },
      { id: 'd48', text: 'If you could be fluent in 3 languages tomorrow, which would you pick and why?' },
      { id: 'd49', text: 'What\'s your favorite word, just for the sound of it?' },
      { id: 'd50', text: 'If you died and came back as an animal, but got to choose the species, what would it be?' },
      { id: 'd51', text: 'What object of yours would betray you if it could talk?' },
      { id: 'd52', text: 'What hobby do you not have only because starting it is too much trouble?' },
      { id: 'd53', text: 'What\'s your favorite "white lie" in social situations?' },
      { id: 'd54', text: 'If you founded a cult, what would the mandatory ritual be?' },
      { id: 'd55', text: 'If you could forget a book/movie/show to experience it for the first time again, which?' },
      { id: 'd56', text: 'What\'s your biggest prejudice against a person\'s name?' },
      { id: 'd57', text: 'What routine of other people\'s do you find completely alien?' },
      { id: 'd58', text: 'What place in the world do you have no interest in visiting and why?' },
      { id: 'd59', text: 'What grammatical error from other people gives you visceral, unjustified rage?' },
      { id: 'd60', text: 'What\'s the silliest visual obsession you have? (e.g., organized folders, tile patterns)' },
      { id: 'd61', text: 'If you were a reality show judge, which stereotype would you be?' },
      { id: 'd62', text: 'What\'s the worst advice you\'d give in good faith?' },
      { id: 'd63', text: 'If you founded a city, what would your first "weird" but non-negotiable law be?' },
      { id: 'd64', text: 'What\'s the worst and the best name of a store/restaurant you\'ve ever seen?' },
      { id: 'd65', text: 'What\'s your worst speech tic?' },
      { id: 'd66', text: 'If you were forced to cosplay right now with what you have at home, who would you be?' },
      { id: 'd67', text: 'What\'s your biggest disconnect with your zodiac sign? (even if you don\'t believe in it)' },
      { id: 'd68', text: 'If you were hired to write the sign for a public bathroom, what would it say?' },
      { id: 'd69', text: 'What\'s your non-negotiable criterion for a good snack?' },
      { id: 'd70', text: 'If you could uninvent one social network, which would it be?' },
      { id: 'd71', text: 'What\'s your opinion on cheese in general?' },
      { id: 'd72', text: 'What small luxury do you only realize you love when you don\'t have it?' },
      { id: 'd73', text: 'If you accidentally inherited a store, which sector would be the most disappointing to inherit?' },
      { id: 'd74', text: 'In which aisle of a grocery store would someone most likely find you?' },
      { id: 'd75', text: 'What\'s the worst backhanded compliment you\'ve ever received?' },
      { id: 'd76', text: 'What birthday cake flavor do you reject?' },
      { id: 'd77', text: 'If I say "think of an apple", how do you imagine it? (a clear image, a taste, a sound...)' },
      { id: 'd78', text: 'If you were an ice cream flavor that nobody picks, which would you be?' },
      { id: 'd79', text: 'What\'s the worst color combination (palette) you\'ve ever seen?' },
      { id: 'd80', text: 'What kind of clothing makes you feel like a "character"?' },
      { id: 'd81', text: 'What\'s the worst kind of waiting? (bank line, doctor\'s office, public transit)' },
      { id: 'd82', text: 'What\'s the most "grandma-like" thing you do without realizing?' },
      { id: 'd83', text: 'If you had to live inside a famous painting for 1 day, which?' },
      { id: 'd84', text: 'If you opened a café whose only rule was "you can only enter with X", what would X be?' },
      { id: 'd85', text: 'What book/movie/show that everyone loves do you think is just okay?' }
    ]
  },
  {
    id: 'grupo', nameKey: 'cat_grupo', questions: [
      { id: 'g1',  text: 'If everyone here got superpowers, who\'s most likely to turn into the villain?' },
      { id: 'g2',  text: 'Who here do you think is living their best phase of life right now?' },
      { id: 'g3',  text: 'If this group started a business together, what would it be and who would do what?' },
      { id: 'g4',  text: 'Which of us has changed the most in the last 5 years?' },
      { id: 'g5',  text: 'If we were a TV show, who\'d be the main character? And who\'d be the comic relief?' },
      { id: 'g6',  text: 'Who here would you call to solve which kind of problem?' },
      { id: 'g7',  text: 'What\'s your favorite memory with someone in this group?' },
      { id: 'g8',  text: 'If we had to survive on a deserted island, what would each person\'s role be?' },
      { id: 'g9',  text: 'Which of us would give the worst love advice with the most confidence?' },
      { id: 'g10', text: 'Who here would you trust to call you at 4am, and who would you never pick up at that hour?' },
      { id: 'g11', text: 'If we had to live together in one house for a month, who\'d be the first to lose it?' },
      { id: 'g12', text: 'Which story from this group will we still be telling 20 years from now?' },
      { id: 'g13', text: 'Who here has changed the most without realizing they\'ve changed?' },
      { id: 'g14', text: 'Who here do you think has the worst secretly favorite song?' },
      { id: 'g15', text: 'If one of us got rich overnight, who would we be most worried about what they\'d do with it?' },
      { id: 'g16', text: 'What was your first impression of each person here? (you can go one by one)' },
      { id: 'g17', text: 'Which of us is most likely to age into that eccentric uncle/aunt everyone loves?' },
      { id: 'g18', text: 'Who here would you "borrow" to introduce to your parents in an emergency?' },
      { id: 'g19', text: 'Which of us would you pick as your escape room partner, and which would you politely decline?' },
      { id: 'g20', text: 'Who here do you think actually knows you the best?' },
      { id: 'g21', text: 'If we were characters at a tabletop RPG session, what class would each of us be?' },
      { id: 'g22', text: 'When did someone in this group surprise you in a way you still remember — for better or worse?' },
      { id: 'g23', text: 'If one of us disappeared without warning, who would notice first?' },
      { id: 'g24', text: 'Which of us do you think is hiding the biggest secret right now, even with zero proof?' },
      { id: 'g25', text: 'Who here would you take on an open-ended road trip with no set destination?' },
      { id: 'g26', text: 'If we were a group of superheroes, what would be everyone\'s collective weakness?' },
      { id: 'g27', text: 'Who here has changed your life the most, in some way big or small?' },
      { id: 'g28', text: 'Which past version of each of us (5 or 10 years ago) would you most want to meet again for one night?' },
      { id: 'g29', text: 'If we had to make a toast to someone in this group right now, who would it be and why?' },
      { id: 'g30', text: 'Which of us would walk out of an apocalypse with the most absurd story to tell?' },
      { id: 'g31', text: 'Which of us talks to AI like it\'s a person?' },
      { id: 'g32', text: 'Who here would you call for: A) a medical emergency; B) an emotional emergency; C) a road emergency?' },
      { id: 'g33', text: 'Who here do you think is holding an opinion about someone in the group that they\'ve never said out loud?' },
      { id: 'g34', text: 'What would the phrase tattooed on each of us\'s forehead be if we were honest?' },
      { id: 'g35', text: 'Who here would the group defend even knowing they\'re wrong?' },
      { id: 'g36', text: 'Which of us is the "emotional thermometer" of the group?' },
      { id: 'g37', text: 'Which of us has the best sense of direction and which gets lost at the mall?' },
      { id: 'g38', text: 'Which of us has the most "leadership material" for the future?' },
      { id: 'g39', text: 'Who would you listen to without questioning even if you deeply disagreed?' },
      { id: 'g40', text: 'Which of us has the best chance of becoming famous for something controversial?' },
      { id: 'g41', text: 'Who here has saved you without knowing they did?' },
      { id: 'g42', text: 'What\'s the "secret talent" you think each of us has?' },
      { id: 'g43', text: 'Who here has the hardest-to-explain music taste?' },
      { id: 'g44', text: 'Which of us would be the worst enemy if they turned villain?' },
      { id: 'g45', text: 'Who here is dealing with more in silence than they show?' },
      { id: 'g46', text: 'Who here inspires you in something specific that you\'ve never said out loud?' },
      { id: 'g47', text: 'Which of us has the most underestimated story?' },
      { id: 'g48', text: 'Who would you call for career advice? And for love advice?' },
      { id: 'g49', text: 'Which of us is most likely to appear in a documentary about some bizarre topic?' },
      { id: 'g50', text: 'Who here do you think has the worst taste in romantic partners?' },
      { id: 'g51', text: 'Which of us would be the worst witness in a courtroom?' },
      { id: 'g52', text: 'Who here would you trust to take care of your plants for 1 month?' },
      { id: 'g53', text: 'Who here drives you most crazy but you keep loving?' },
      { id: 'g54', text: 'Which of us is the most secretly resentful?' },
      { id: 'g55', text: 'If we could swap one trait of each of us, which would be the most obvious one?' },
      { id: 'g56', text: 'Who here knows what they want from life the most?' },
      { id: 'g57', text: 'Which of us looks most like they\'re living a secret life?' },
      { id: 'g58', text: 'Who here do you want still in your life when you\'re 70?' },
      { id: 'g59', text: 'If we had to nominate ONE person in the group to write a book, who would it be and what would the likely title be?' },
      { id: 'g60', text: 'What story from this group still gives secondhand embarrassment to tell to outsiders?' },
      { id: 'g61', text: 'What\'s the place that holds the most memories of this group?' },
      { id: 'g62', text: 'What does this group have that other groups in your life don\'t?' },
      { id: 'g63', text: 'How do you think this group would be seen by an outsider observer?' },
      { id: 'g64', text: 'What\'s the most beautiful thing that happened in this group in the last 12 months?' },
      { id: 'g65', text: 'If this group were a living organism, which organ would each of us be?' },
      { id: 'g66', text: 'What kind of new person would fit in this group, and what kind would never work?' },
      { id: 'g67', text: 'If this group won a collective award, what would the category be?' },
      { id: 'g68', text: 'What are the 3 unspoken rules of this group?' },
      { id: 'g69', text: 'On what topic do we disagree most when it comes up?' },
      { id: 'g70', text: 'What collective decision would this group make easily and which would be chaos?' },
      { id: 'g71', text: 'What\'s the most controversial opinion floating around this group?' },
      { id: 'g72', text: 'If we spent 1 month together in a beach house, what would the inevitable big fight be about?' },
      { id: 'g73', text: 'If we started a podcast right now, what would the topic be?' },
      { id: 'g74', text: 'If this group joined a collective reality show, would we win or be eliminated first?' },
      { id: 'g75', text: 'If we could veto one collective personality trait of the group, which would it be?' },
      { id: 'g76', text: 'Is there a compliment you wanted to give to someone here right now and never have?' },
      { id: 'g77', text: 'Did something happen in this group that changed how you see people?' },
      { id: 'g78', text: 'When this group frustrates you, what\'s usually the cause?' },
      { id: 'g79', text: 'What\'s your favorite memory involving just you and ONE other person from here?' },
      { id: 'g80', text: 'Do you feel more yourself or less yourself in this group?' },
      { id: 'g81', text: 'If we had to adopt a "collective pet", what and who would take care of what?' },
      { id: 'g82', text: 'What\'s the first adjective that comes to mind when you think of this group collectively?' },
      { id: 'g83', text: 'What food matches the vibe of this group most?' },
      { id: 'g84', text: 'What\'s the oldest memory you have involving everyone here?' },
      { id: 'g85', text: 'Is there someone here you wish you knew better?' },
      { id: 'g86', text: 'What changed in you since this group came into your life?' },
      { id: 'g87', text: 'What\'s the topic this group opens up that other groups of yours never would?' },
      { id: 'g88', text: 'What does this group need to do more of, and what less?' },
      { id: 'g89', text: 'If we had to write a manual for a new member to join, what would the first rule be?' },
      { id: 'g90', text: 'What\'s your biggest gratitude regarding this group?' },
      { id: 'g91', text: 'Is there someone here with whom you have a specific affection you don\'t have with anyone else?' }
    ]
  }
];


export const DECKS = {
  pt: PT_DECKS,
  en: EN_DECKS,
  // jp: JP_DECKS,
};